In [1]:
from Graph import Graph
from GraphDijkstra import GraphDijkstra
import numpy as np
from random import randint
from time import time
from parserCities import get_matrice_from_file, get_cities_positions_from_file
import math

# Exo 1

In [2]:
#charger le graph dijkstra
# le contenu du fichier graph.txt est de ce style :
# node1-poid-node2 // relation dans les deux sens
# node2-poid->node1 // sens de la relation
g = GraphDijkstra("./graph.txt")
rows = g.dijkstra_table(start="s") #! replace the start by the start label !
n_arc = g.get_nb_arcs()
n_sommet = g.get_nb_sommets()
print(f"Combien l’algorithme fait-il d’opérations sur ce graphe ? \n (nb sommets + nb arcs) x log(nb sommets) = ({n_sommet}+{n_arc}) x log({n_sommet}) = {(n_sommet + n_arc) * math.log(n_sommet) } ")

s    | a    | b    | c    | d   
-    | 8(s) | inf  | inf  | 2(s)
inf  | 7(d) | inf  | 4(d) | -   
inf  | 5(c) | 7(c) | -    | inf 
inf  | -    | 7(c) | inf  | inf 
inf  | inf  | -    | inf  | inf 
Combien l’algorithme fait-il d’opérations sur ce graphe ? 
 (nb sommets + nb arcs) x log(nb sommets) = (5+7) x log(5) = 19.313254949209202 


In [3]:
# floyd
s_order = [s.label for s in g.sommets]
print(f"ATTENTION: ordre des sommets : {s_order}")

w, p = g.floyd()

print(f"\nRésultat final :\nw = {w}\n\n p = {p}")

ATTENTION: ordre des sommets : ['s', 'a', 'b', 'c', 'd']

Initialisation des deux matrices :
w = [[ 0.  8. inf inf  2.]
 [ 8.  0.  3.  1.  5.]
 [inf  3.  0.  3. inf]
 [inf  1.  3.  0.  2.]
 [ 2.  5. inf  2.  0.]]

 p = [[0. 1. 0. 0. 4.]
 [0. 0. 2. 3. 4.]
 [0. 1. 0. 3. 0.]
 [0. 1. 2. 0. 4.]
 [0. 1. 0. 3. 0.]]



Résultat final :
w = [[0. 5. 7. 4. 2.]
 [5. 0. 3. 1. 3.]
 [7. 3. 0. 3. 5.]
 [4. 1. 3. 0. 2.]
 [2. 3. 5. 2. 0.]]

 p = [[0. 4. 4. 4. 4.]
 [4. 0. 2. 3. 3.]
 [4. 1. 0. 3. 3.]
 [4. 1. 2. 0. 4.]
 [0. 3. 3. 3. 0.]]


**Pourquoi l’algorithme de Dijkstra ne marche pas si le poids de l’arête du
sommet « a » au sommet « c » vaut -1 ? Est-ce que l’algorithme Floyd
marche avec ce poids ?**

L'algorithme de Dijkstra ne fonctionne pas avec des arêtes de poids négatif car il suppose que les distances les plus courtes sont non négatives. En revanche, l'algorithme de Floyd-Warshall peut gérer les poids d'arêtes négatifs, bien que sa complexité en temps puisse être élevée dans certains cas.

# Exo 2

**Q1 Le plus grand sous-graphe est-il un K3 ? un K4 ? ou un K5 ? Justifier.**
Sous graphe complet est un ensemble de sommets du graph ou tout les sommets sont relié entre eux. K2 = 2 sommets reliés entre eux, K3 = 3 sommets reliés entre eux etc... Il faut regarder le graphe.

**Q2 Donner le nombre de sous-graphes K3 de ce graphe, le nombre de sous-graphes K4 de ce graphe et le nombre de sous-graphes K5 de ce graphe.**

Pareil regarder le graphe.

**Q3 En général si le graphe contient n sommets combien a-t-on au maximum de sous-graphes K3, de sous-graphes K4 et plus généralement de sous-graphes Km pour m<n+1 ? Pour quels graphes va-t-on atteindre ce maximum ?**

$$ \begin{pmatrix}
n \\
m
\end{pmatrix} = \frac{n!}{m! (n - m)!} $$

On attendra le maximum si le graph est complet.

In [4]:
n = 7
m = 3 # valeur de K donc ici on cherche K3

maxi = math.factorial(n) / (math.factorial(m) * math.factorial(n-m))

print(f"Combien de K{m} peut-on trouver dans ce graphe ? {maxi} ")

Combien de K3 peut-on trouver dans ce graphe ? 35.0 


In [5]:
#densité d’un graphe
e = 15 # arretes (edges)
v = 7  # sommets (vertex)

print(f"Quelle est la densité de ce graphe ? {(2*e)/(v*(v-1))}")
print("Si 0 alors le graphe n'a pas d'arrète (noeuds isolés), si 1 alors le graphe est complet")

Quelle est la densité de ce graphe ? 0.7142857142857143
Si 0 alors le graphe n'a pas d'arrète (noeuds isolés), si 1 alors le graphe est complet


**Est-ce que la densité des sous-graphes du graphe que l’on étudie permet de trouver les sous-graphes complets ?**

Oui, on calcule la densité sur tout les sous graphes possibles pour voir si c'est égale à 1.

# Exo 3

On travaille sur un graphe non orienté avec une seule composante connexe qui
contient 6 sommets. On sait que les degrés de 5 des sommets sont respectivement
1, 2, 3, 4 et 5. Quel est le degré du sixième sommet ? Justifier.

*demerdez vous, dessinez le graph en partant des sommets de degré le plus élevé (5, puis 4 etc..)*

# Exo 4

Une usine fabrique deux types de glaces à la vanille, l’une normale et l’autre sans
sucre à partir de trois ingrédients : Vanille, Lait et Sucre.

Un bac de glace normale se compose avec les proportions suivantes **1kg de Vanille**, **2kg de lait** et **1kg de sucre**

un bac de glace sans sucre se compose avec les proportions suivantes **2kg de Vanille**, **1kg de lait** et **0kg de sucre**.

Au début de la production on a **800kg de Vanille**, **700kg de lait** et **300kg de sucre.**

La vente d’un kg de glace normale rapporte **4 euros** et la vente d’un kg de glace sans sucre rapporte **5 euros.**
Le directeur de l’usine de fabrication de glaces souhaite **maximiser le profit sur les glaces à la vanille.** Que proposez-vous comme solution ?

In [25]:
from simplex import parse, simplex
# variable une seule lettre maj ou min
# ex = equation numéro x

#n = normale et s = sans sucre
m1, vars = parse(["max z = 4n + 5s", # nature = 4€ et sans sucre = 5€
                "2n + s <= 700", # e1 (lait)
                "n + 2s <= 800", # e2 (vanille)
                "n <= 300"]) # e3 (sucre)

print(f" matrice du systeme : \n {m1} \n")
print(f"vars dans l'ordre : {vars} \n")

m2, final = simplex(m1, vars)
print(f"matrice final : \n {m2} \n")
print(f"Pour maximiser les valeurs restante une fois le processus terminé sont les suivantes")
for k,v in final.items():
    print(f"{k} = {v}")

 matrice du systeme : 
 [[  2.   1.   1.   0.   0. 700.]
 [  1.   2.   0.   1.   0. 800.]
 [  1.   0.   0.   0.   1. 300.]
 [  4.   5.   0.   0.   0.   0.]] 

vars dans l'ordre : {'n': 0, 's': 1, 'e1': 2, 'e2': 3, 'e3': 4} 

matrice final : 
 [[    1.        0.        0.667    -0.333     0.      200.   ]
 [    0.        1.       -0.333     0.667     0.      300.   ]
 [    0.        0.       -0.667     0.333     1.      100.   ]
 [    0.        0.       -1.       -2.        0.    -2300.   ]] 

Pour maximiser les valeurs restante une fois le processus terminé sont les suivantes
n = 200.0
s = 300.0
e3 = 100.0


In [7]:
# flo si jamais ça tombe
g_flow = GraphDijkstra("./flo.txt")
flow, mat = g_flow.getFlow()

print(f"flow = {flow}\nmat =\n {mat}")

flow = 12.0
mat =
 [[0. 0. 2. 0. 0. 0.]
 [6. 0. 0. 0. 3. 0.]
 [6. 0. 0. 0. 0. 0.]
 [0. 3. 3. 0. 0. 0.]
 [0. 3. 3. 0. 0. 2.]
 [0. 0. 0. 6. 6. 0.]]
