In [1]:
from Graph import Graph
from GraphDijkstra import GraphDijkstra
import numpy as np
from random import randint
from time import time
from parserCities import get_matrice_from_file, get_cities_positions_from_file
import math

# Exo 1

In [2]:
#charger le graph dijkstra
# le contenu du fichier graph.txt est de ce style :
# node1-poid-node2 // relation dans les deux sens
# node2-poid->node1 // sens de la relation
g = GraphDijkstra("./graph.txt")
rows = g.dijkstra_table(start="s") #! replace the start by the start label !
n_arc = g.get_nb_arcs()
n_sommet = g.get_nb_sommets()
print(f"Combien l’algorithme fait-il d’opérations sur ce graphe ? \n (nb sommets + nb arcs) x log(nb sommets) = ({n_sommet}+{n_arc}) x log({n_sommet}) = {(n_sommet + n_arc) * math.log(n_sommet) } ")

s    | a    | b    | c    | d   
-    | 8(s) | inf  | inf  | 2(s)
inf  | 7(d) | inf  | 4(d) | -   
inf  | 5(c) | 7(c) | -    | inf 
inf  | -    | 7(c) | inf  | inf 
inf  | inf  | -    | inf  | inf 
Combien l’algorithme fait-il d’opérations sur ce graphe ? 
 (nb sommets + nb arcs) x log(nb sommets) = (5+7) x log(5) = 19.313254949209202 


In [3]:
# floyd
s_order = [s.label for s in g.sommets]
print(f"ATTENTION: ordre des sommets : {s_order}")

w, p = g.floyd()

print(f"\nRésultat final :\nw = {w}\n\n p = {p}")

ATTENTION: ordre des sommets : ['s', 'a', 'b', 'c', 'd']

Initialisation des deux matrices :
w = [[ 0.  8. inf inf  2.]
 [ 8.  0.  3.  1.  5.]
 [inf  3.  0.  3. inf]
 [inf  1.  3.  0.  2.]
 [ 2.  5. inf  2.  0.]]

 p = [[0. 1. 0. 0. 4.]
 [0. 0. 2. 3. 4.]
 [0. 1. 0. 3. 0.]
 [0. 1. 2. 0. 4.]
 [0. 1. 0. 3. 0.]]



Résultat final :
w = [[0. 5. 7. 4. 2.]
 [5. 0. 3. 1. 3.]
 [7. 3. 0. 3. 5.]
 [4. 1. 3. 0. 2.]
 [2. 3. 5. 2. 0.]]

 p = [[0. 4. 4. 4. 4.]
 [4. 0. 2. 3. 3.]
 [4. 1. 0. 3. 3.]
 [4. 1. 2. 0. 4.]
 [0. 3. 3. 3. 0.]]


**Pourquoi l’algorithme de Dijkstra ne marche pas si le poids de l’arête du
sommet « a » au sommet « c » vaut -1 ? Est-ce que l’algorithme Floyd
marche avec ce poids ?**

L'algorithme de Dijkstra ne fonctionne pas avec des arêtes de poids négatif car il suppose que les distances les plus courtes sont non négatives. En revanche, l'algorithme de Floyd-Warshall peut gérer les poids d'arêtes négatifs, bien que sa complexité en temps puisse être élevée dans certains cas.

# Exo 2

**Q1 Le plus grand sous-graphe est-il un K3 ? un K4 ? ou un K5 ? Justifier.**
Sous graphe complet est un ensemble de sommets du graph ou tout les sommets sont relié entre eux. K2 = 2 sommets reliés entre eux, K3 = 3 sommets reliés entre eux etc... Il faut regarder le graphe.

**Q2 Donner le nombre de sous-graphes K3 de ce graphe, le nombre de sous-graphes K4 de ce graphe et le nombre de sous-graphes K5 de ce graphe.**

Pareil regarder le graphe.

**Q3 En général si le graphe contient n sommets combien a-t-on au maximum de sous-graphes K3, de sous-graphes K4 et plus généralement de sous-graphes Km pour m<n+1 ? Pour quels graphes va-t-on atteindre ce maximum ?**

$$ \begin{pmatrix}
n \\
m
\end{pmatrix} = \frac{n!}{m! (n - m)!} $$

On attendra le maximum si le graph est complet.

In [4]:
n = 7
m = 3 # valeur de K donc ici on cherche K3

maxi = math.factorial(n) / (math.factorial(m) * math.factorial(n-m))

print(f"Combien de K{m} peut-on trouver dans ce graphe ? {maxi} ")

Combien de K3 peut-on trouver dans ce graphe ? 35.0 


In [5]:
#densité d’un graphe
e = 15 # arretes (edges)
v = 7  # sommets (vertex)

print(f"Quelle est la densité de ce graphe ? {(2*e)/(v*(v-1))}")
print("Si 0 alors le graphe n'a pas d'arrète (noeuds isolés), si 1 alors le graphe est complet")

Quelle est la densité de ce graphe ? 0.7142857142857143
Si 0 alors le graphe n'a pas d'arrète (noeuds isolés), si 1 alors le graphe est complet


**Est-ce que la densité des sous-graphes du graphe que l’on étudie permet de trouver les sous-graphes complets ?**

Oui, on calcule la densité sur tout les sous graphes possibles pour voir si c'est égale à 1.

# Exo 3

On travaille sur un graphe non orienté avec une seule composante connexe qui
contient 6 sommets. On sait que les degrés de 5 des sommets sont respectivement
1, 2, 3, 4 et 5. Quel est le degré du sixième sommet ? Justifier.

*demerdez vous, dessinez le graph en partant des sommets de degré le plus élevé (5, puis 4 etc..)*

# Exo 4

In [6]:
import numpy as np


def simplex_algorithm(c, A, b):
    m, n = A.shape
    tableau = np.zeros((m + 1, n + m + 1))

    # Initialize tableau
    tableau[:-1, :n] = A
    tableau[:-1, -1] = b
    tableau[-1, :n] = -c
    tableau[-1, -1] = 0

    while any(tableau[-1, :n] < 0):
        # Choose entering variable (column k with the most negative coefficient)
        entering_var = np.argmin(tableau[-1, :n])

        # Choose leaving variable (row l with the minimum ratio b[i]/A[i, k] where A[i, k] > 0)
        ratios = tableau[:-1, -1] / tableau[:-1, entering_var]
        leaving_var = np.argmin(ratios)

        # Update the tableau
        pivot = tableau[leaving_var, entering_var]
        tableau[leaving_var, :] /= pivot
        for i in range(m + 1):
            if i != leaving_var:
                tableau[i, :] -= tableau[i, entering_var] * \
                    tableau[leaving_var, :]

    # Extract optimal solution and objective value
    solution = tableau[:-1, -1]
    objective_value = -tableau[-1, -1]

    return solution, objective_value


# Test the implementation with the provided example

c = np.array([4, 5, 0, 0, 0, 0])
A = np.array([[1, 2, 1, 0, 0, 0],
              [2, 1, 0, 1, 0, 0],
              [1, 0, 0, 0, 1, 0]])
b = np.array([800, 700, 300])

solution, objective_value = simplex_algorithm(c, A, b)

print("Optimal Solution:", solution)
print("Optimal Objective Value:", objective_value)

Optimal Solution: [300. 200. 100.]
Optimal Objective Value: -2300.0


C:\Users\hrey2\AppData\Local\Temp\ipykernel_14796\3001761302.py:19: RuntimeWarning: divide by zero encountered in divide
  ratios = tableau[:-1, -1] / tableau[:-1, entering_var]


In [7]:
# flo si jamais ça tombe
g_flow = GraphDijkstra("./flo.txt")
flow, mat = g_flow.getFlow()

print(f"flow = {flow}\nmat =\n {mat}")

flow = 12.0
mat =
 [[0. 0. 2. 0. 0. 0.]
 [6. 0. 0. 0. 3. 0.]
 [6. 0. 0. 0. 0. 0.]
 [0. 3. 3. 0. 0. 0.]
 [0. 3. 3. 0. 0. 2.]
 [0. 0. 0. 6. 6. 0.]]
